import type { Activity, SkillKey } from "@/types";

import { ACTIVITY_EXAMPLES } from "./activity-examples";
import { ACTIVITY_HOOKS } from "./activity-hooks";
import { ACTIVITY_ICONS } from "./activity-icons";
import { ACTIVITY_TABLER_ICONS } from "./activity-tabler-icons";

/**
 * The Fokus activity library: 64 activities, 8 per skill, content
 * copied verbatim from SPEC §8. Order: by skill, then by id within skill.
 *
 * The `example`, `hook`, and `iconName` fields for each activity live
 * in sibling files and are merged in at module load. Keeping them
 * separate keeps this file scannable as a content catalog.
 */
const ACTIVITIES_BASE: Array<
  Omit<Activity, "example" | "iconName" | "hook" | "icon">
> = [
  // ============================================================
  // CURIOSITY
  // ============================================================
  {
    id: "cu1",
    title: "The Why Chain",
    skill: "curiosity",
    duration: 10,
    difficulty: 2,
    languageLoad: "medium",
    ageRange: [6, 10],
    requires: "nothing",
    description: `Pick anything they point to and ask "why" five times together.`,
    hiddenCurriculum: `Asking why is how kids learn to look behind the obvious. Most are told to stop around this age, and the muscle goes quiet.`,
    howTo: `Wait for something they point at. Ask why. When they answer, ask why again about that, five times total.`,
    watchFor: `Did they stay curious or get frustrated? Did they invent a theory? Did they ask their own follow-up question without you prompting?`,
    oneLineToSay: `Most kids stop asking why around your age. Let's stay weird and keep asking. Drop once. Don't repeat.`,
    trap: `Giving the answer. The "I don't know, let's wonder" is the entire lesson. If you Google it inside 5 minutes, you taught the opposite.`,
    adapt: {
      easier: `3 layers. Celebrate the shrug.`,
      harder: `7+ layers, branch into "what if it were different?"`,
    },
    worksWellWith: ["science", "nature", "vehicles", "animals"],
  },
  {
    id: "cu2",
    title: "Take It Apart",
    skill: "curiosity",
    duration: 25,
    difficulty: 2,
    languageLoad: "low",
    ageRange: [6, 10],
    requires: "objects-at-home",
    description: `Open up an old pen, broken toy, or torch together. Look at what's inside.`,
    hiddenCurriculum: `Things are made of parts, and parts have jobs. Knowing that is the first step toward figuring out how anything works.`,
    howTo: `Find a safe object to open up. Let them do the unscrewing themselves. Ask what each piece is for.`,
    watchFor: `Their patience with small parts. Whether they want to know what each piece *does* vs. just see inside.`,
    oneLineToSay: `Everything you see was designed by someone. They figured out the pieces. You can too.`,
    trap: `Doing it for them when they fumble. The fumbling is the learning. Hands learn what eyes can't.`,
    adapt: {
      easier: `Just one component, like the spring from a pen.`,
      harder: `An old remote, a broken toy with circuit boards.`,
    },
    worksWellWith: ["building/lego", "drawing", "vehicles", "how things work"],
  },
  {
    id: "cu3",
    title: "Question Jar",
    skill: "curiosity",
    duration: 5,
    difficulty: 1,
    languageLoad: "medium",
    ageRange: [5, 10],
    requires: "paper-pen",
    description: `Every day, they put one question they had today into a physical jar. Once a week, you investigate one.`,
    hiddenCurriculum: `Most homes train kids out of asking by around age 8. Saving their questions tells them the questions are worth keeping.`,
    howTo: `Keep a jar where they see it. Each evening, ask for one question from their day. Once a week, look one up together.`,
    watchFor: `Quality of questions over weeks. Does the child start *noticing more things to wonder about* during the day?`,
    oneLineToSay: `Questions are how we make the world bigger. Said once when starting the jar.`,
    trap: `Investigating every question. That overburdens the practice. One a week. The jar is mostly a *receptacle*, not a to-do list.`,
    adapt: {
      easier: `Model first. Write your own question on day 1.`,
      harder: `Ask for 2 questions a day, themed weeks.`,
    },
    worksWellWith: ["drawing", "stories", "science"],
  },
  {
    id: "cu4",
    title: "How Does It Work?",
    skill: "curiosity",
    duration: 15,
    difficulty: 2,
    languageLoad: "high",
    ageRange: [7, 10],
    requires: "nothing",
    description: `Pick one everyday thing and figure out how it works together. No Googling.`,
    hiddenCurriculum: `Forming a guess and then checking it is how understanding actually gets built. The guess is the part that matters, even when it is wrong.`,
    howTo: `Pick one everyday thing whose insides are a mystery. Both of you guess how it works on paper. Only after that, look it up.`,
    watchFor: `Whether their theories make internal sense, even if wrong. That's reasoning, regardless of the answer.`,
    oneLineToSay: `Getting it wrong with a good guess is better than getting it right by being told.`,
    trap: `Rushing to look up the answer. The wrong theory is the lesson. Comparing it to the truth is how understanding gets built.`,
    adapt: {
      easier: `Something visible like a tap or a doorknob.`,
      harder: `Something abstract: how does wifi work? How does sleep work?`,
    },
    worksWellWith: ["drawing", "science", "building/lego", "how things work"],
  },
  {
    id: "cu5",
    title: "Walk and Notice",
    skill: "curiosity",
    duration: 15,
    difficulty: 1,
    languageLoad: "medium",
    ageRange: [5, 10],
    requires: "outdoors",
    description: `A 10-minute walk where the only rule is: spot three weird things.`,
    hiddenCurriculum: `A street stops being visible after enough walks. Slowing down with a job to notice rebuilds the seeing.`,
    howTo: `Take a 10-minute walk together. They have to spot three things they have never noticed before. For each one, ask why they think it looks like that.`,
    watchFor: `Does their *noticing radius* expand over weeks? Do they start pointing things out unprompted on regular walks?`,
    oneLineToSay: `Most people walk the same street a thousand times and never see it. We're going to see it.`,
    trap: `Helping them find things. The friction of looking IS the practice. Stay silent.`,
    adapt: {
      easier: `Find 1 weird thing in great detail.`,
      harder: `Find 5, name a category for each (textures / patterns / human-made / natural / accidental).`,
    },
    worksWellWith: ["outdoor exploring", "nature", "walking", "drawing"],
  },
  {
    id: "cu6",
    title: "Stranger Question",
    skill: "curiosity",
    duration: 10,
    difficulty: 3,
    languageLoad: "high",
    ageRange: [7, 10],
    requires: "nothing",
    description: `They think of one question to ask a person who knows something they don't.`,
    hiddenCurriculum: `Asking a stranger a real question takes courage and a bit of tact. Building that early makes it ordinary later.`,
    howTo: `Pick someone with a job they're curious about. They prepare one question about that work. They ask it themselves while you stay back.`,
    watchFor: `Courage to ask. Quality of follow-up. How they feel about it afterward.`,
    oneLineToSay: `Every person you'll ever meet knows something you don't. Asking is how you collect.`,
    trap: `Prepping them too much. One question, in their own words, even if awkward. Polish kills authenticity at this age.`,
    adapt: {
      easier: `Ask a family member first.`,
      harder: `2 people, same topic, compare their answers.`,
    },
    worksWellWith: ["meeting people", "social", "languages"],
  },
  {
    id: "cu7",
    title: "What's Inside?",
    skill: "curiosity",
    duration: 10,
    difficulty: 2,
    languageLoad: "medium",
    ageRange: [6, 10],
    requires: "nothing",
    description: `Pick a closed object (a mango, light bulb, your phone). Both of you guess what's inside before opening or looking it up.`,
    hiddenCurriculum: `Picturing something before checking reality is how engineers and scientists think. Practice it on a mango and the habit transfers.`,
    howTo: `Choose something closed: a mango, a light bulb, an old phone. Both of you draw what you think is inside, no peeking. Compare your drawings, then open it.`,
    watchFor: `Detail in their guess. Do they build a theory or just say "stuff"?`,
    oneLineToSay: `Guessing isn't wrong. Guessing is the start of figuring out.`,
    trap: `Correcting their drawing. Compare reality to their guess, but don't grade the guess.`,
    adapt: {
      easier: `Simple things like a banana, a pencil.`,
      harder: `A human eye, a clock, a battery.`,
    },
    worksWellWith: ["drawing", "science", "how things work"],
  },
  {
    id: "cu8",
    title: "Animal Mystery",
    skill: "curiosity",
    duration: 15,
    difficulty: 1,
    languageLoad: "medium",
    ageRange: [5, 10],
    requires: "nothing",
    description: `Pick an animal. Together, list 5 weird things you don't know about it. Then find them out.`,
    hiddenCurriculum: `Most kids learn to hide what they don't know. Saying it together makes not-knowing the start of finding out instead.`,
    howTo: `Together pick an animal. Make a list of five things neither of you knows about it. Look them up, then choose the one that surprised you most.`,
    watchFor: `Their engagement with not-knowing. Many kids hate admitting it. This normalizes it.`,
    oneLineToSay: `Not knowing is the start of knowing. Pretending to know stops it.`,
    trap: `Letting them only pick "their favorite animal" each time. Push variety: a worm, a moth, a bat.`,
    adapt: {
      easier: `3 questions, picture-rich answers.`,
      harder: `10 questions, then they explain it to another family member.`,
    },
    worksWellWith: ["animals", "nature", "stories", "drawing"],
  },

  // ============================================================
  // LANGUAGE CONFIDENCE
  // ============================================================
  {
    id: "la1",
    title: "Tell Me About Your Day (in English)",
    skill: "language",
    duration: 10,
    difficulty: 1,
    languageLoad: "high",
    ageRange: [6, 10],
    requires: "nothing",
    description: `5 minutes where they tell you about their day, only in English. You don't correct.`,
    hiddenCurriculum: `Fluency before accuracy. Most ESL kids freeze because they're afraid of being wrong. Removing correction unlocks the muscle.`,
    howTo: `Set a 5-minute timer. They talk about anything from their day, only in English. If they get stuck, they can mime, gesture, or use one Hindi word. You supply the English word and move on. NEVER correct grammar. End by saying "I liked when you said ___."`,
    watchFor: `Length of sentences over weeks. Risk-taking with new words. Do they stop completely or push through stuck moments?`,
    oneLineToSay: `Pick one specific thing they said well: When you said 'and then suddenly,' that was great. Specific praise > general praise.`,
    trap: `Correcting grammar or pronunciation mid-flow. This is the single fastest way to kill English confidence. Wait. Even at the end, mention zero or one thing.`,
    adapt: {
      easier: `2 minutes, you ask questions they answer in single words or short phrases.`,
      harder: `10 minutes, follow-up questions.`,
    },
    worksWellWith: ["stories", "talking", "anything"],
  },
  {
    id: "la2",
    title: "Picture Description",
    skill: "language",
    duration: 10,
    difficulty: 1,
    languageLoad: "high",
    ageRange: [6, 10],
    requires: "nothing",
    description: `Show them any photo or picture book image. They describe it in English for 1 minute.`,
    hiddenCurriculum: `Vocabulary recall under low pressure. Naming things you see is easier than narrating; this builds the bridge.`,
    howTo: `Pick a busy image (a picture book page, a photo from your phone). They describe everything they see in English. Time 1 minute. No corrections. Count how many things they named. Next time, try to beat the count.`,
    watchFor: `Vocabulary range. Do they take risks naming things they're not sure of?`,
    oneLineToSay: `You named [X] things. That's more than yesterday. Or: Every new word is a new room in your head.`,
    trap: `Picking images that are too simple. A busy, weird image gives more material.`,
    adapt: {
      easier: `Simple image, 30 seconds, you point to things.`,
      harder: `2 minutes, abstract or emotional image.`,
    },
    worksWellWith: ["drawing", "stories", "animals", "anything visual"],
  },
  {
    id: "la3",
    title: "Story Continue",
    skill: "language",
    duration: 10,
    difficulty: 2,
    languageLoad: "high",
    ageRange: [6, 10],
    requires: "nothing",
    description: `You start a story in English with one line. They continue with one line. Back and forth.`,
    hiddenCurriculum: `Spontaneous English with creative pressure. The story scaffolds the language. They think about plot, the English comes along.`,
    howTo: `Start: "There was a boy who found a strange door in his school." They add the next line. You add the next. Keep going for 10 turns. Silly is good. End the story together.`,
    watchFor: `Do they extend the plot or just repeat? Risk-taking with words.`,
    oneLineToSay: `We just wrote a story together. You and me. Said at the end.`,
    trap: `Hijacking the plot when their turn is weak. Let weird, illogical, silly plots stand. The point is *speaking*, not literary quality.`,
    adapt: {
      easier: `Just 3 turns, you scaffold heavily.`,
      harder: `Longer turns, more complex plots.`,
    },
    worksWellWith: ["stories", "pretend play", "drawing"],
  },
  {
    id: "la4",
    title: "Word of the Day",
    skill: "language",
    duration: 5,
    difficulty: 1,
    languageLoad: "medium",
    ageRange: [6, 10],
    requires: "nothing",
    description: `One new English word a day. They must use it 3 times before bed.`,
    hiddenCurriculum: `Active vocabulary > passive vocabulary. Most ESL learners know thousands of words they never use. Using > recognizing.`,
    howTo: `Morning: pick a word they don't know (start with concrete: "enormous," "ancient," "fragile"). Explain it with an example. Their mission: use it 3 times during the day. Track count out loud.`,
    watchFor: `Do they use it correctly? Do they start collecting words?`,
    oneLineToSay: `Words you USE are words you OWN. The rest are just visitors.`,
    trap: `Picking abstract words too early. Concrete words first ("enormous"), abstract ones later ("frustrated").`,
    adapt: {
      easier: `Super simple, count of 2 uses.`,
      harder: `Abstract words, use in 5 different sentences.`,
    },
    worksWellWith: ["stories", "drawing", "anything"],
  },
  {
    id: "la5",
    title: "Order Something Yourself",
    skill: "language",
    duration: 10,
    difficulty: 3,
    languageLoad: "high",
    ageRange: [7, 10],
    requires: "outdoors",
    description: `At a shop or restaurant, they order or ask for something fully in English.`,
    hiddenCurriculum: `Confidence > fluency. Doing this once gives more confidence than 10 worksheets. The world rewards courage to speak.`,
    howTo: `Plan beforehand what they'll say. Practice once at home. Then they do it alone while you stand close but silent. Hug afterward regardless of how it went.`,
    watchFor: `Their courage level. The decision to speak IS the thing.`,
    oneLineToSay: `You just talked to a stranger in English. That's bigger than it feels. Said immediately after, then drop it.`,
    trap: `Coaching from the sidelines. Whisper-prompting. They feel monitored and freeze. Stand 2 meters back, look at your phone, let them do it.`,
    adapt: {
      easier: `Just say "thank you" to the shopkeeper.`,
      harder: `A full conversation, ask 2 follow-up questions.`,
    },
    worksWellWith: ["outdoor exploring", "going to shops", "meeting people"],
  },
  {
    id: "la6",
    title: "Read Aloud Time",
    skill: "language",
    duration: 15,
    difficulty: 2,
    languageLoad: "high",
    ageRange: [6, 10],
    requires: "objects-at-home",
    description: `They read one page aloud from a story book. You read the next. Alternate.`,
    hiddenCurriculum: `Reading aloud uses different brain circuits than silent reading. It integrates speaking confidence with comprehension. Modeling expressive reading shows what "good" sounds like.`,
    howTo: `Pick a book one level *below* their school level (build confidence, not stretch). They read a page. You read the next with expression: voices, pauses, drama. Don't correct mispronunciations mid-flow. Wait till the end, and mention only 1 if any.`,
    watchFor: `Expression, not accuracy. Do they start putting emotion into voices over weeks?`,
    oneLineToSay: `Reading isn't just decoding letters. It's bringing the story alive. Said once, then just model it.`,
    trap: `Picking a book at their stretch level. Confidence wins over difficulty here. They should sound good to themselves.`,
    adapt: {
      easier: `Just one paragraph, you read most of the page.`,
      harder: `A harder book, full chapter.`,
    },
    worksWellWith: ["stories", "reading", "drawing"],
  },
  {
    id: "la7",
    title: "Teach Me Something",
    skill: "language",
    duration: 10,
    difficulty: 2,
    languageLoad: "high",
    ageRange: [7, 10],
    requires: "nothing",
    description: `They teach you something they know, only in English. You play the student.`,
    hiddenCurriculum: `Explaining is the deepest form of knowing. When they have to organize their thoughts to teach you, comprehension solidifies and English flows because the focus is the *thing*, not the language.`,
    howTo: `Topic: anything they know (a game, a school subject, a YouTube thing they watched). They must explain it to you in English. You ask "student" questions: "But why?" "Can you show me?" Take it seriously.`,
    watchFor: `Clarity of explanation. Do they organize their thoughts or jump around?`,
    oneLineToSay: `You explained that better than my teachers used to. Specific praise.`,
    trap: `Being a fake-impressed parent. Kids smell that. Be an actual curious student. Ask real questions.`,
    adapt: {
      easier: `Just one fact, you do most of the asking.`,
      harder: `A complex topic, they teach for 5 full minutes.`,
    },
    worksWellWith: ["stories", "anything they're into"],
  },
  {
    id: "la8",
    title: "Phone Call Practice",
    skill: "language",
    duration: 10,
    difficulty: 3,
    languageLoad: "high",
    ageRange: [7, 10],
    requires: "nothing",
    description: `They call a relative on the phone and have a 3-minute conversation in English.`,
    hiddenCurriculum: `Phone English is harder than face-to-face. No gestures, no context. Mastering it builds serious confidence.`,
    howTo: `Pre-arrange with a relative (grandparent, uncle, family friend) who'll be patient. They call. Prep one question and one thing to share. Hand them the phone. Don't coach during the call.`,
    watchFor: `Were they able to keep it going? Did they panic and hand the phone over?`,
    oneLineToSay: `Phones are harder than face to face. You handled it.`,
    trap: `Listening on speaker and reacting. Let them have the call in private. Privacy = ownership.`,
    adapt: {
      easier: `Video call, longer.`,
      harder: `Two calls in one week to different people.`,
    },
    worksWellWith: ["family", "meeting people"],
  },

  // ============================================================
  // EMOTIONAL AWARENESS
  // ============================================================
  {
    id: "em1",
    title: "Name the Feeling",
    skill: "emotional",
    duration: 5,
    difficulty: 1,
    languageLoad: "medium",
    ageRange: [5, 10],
    requires: "nothing",
    description: `Three times today, ask them to name what they're feeling, and the intensity 1 to 10.`,
    hiddenCurriculum: `Emotions become manageable once named. Unnamed emotions run the show. This is the foundation of all adult emotional regulation.`,
    howTo: `At random moments throughout the day: "What are you feeling right now?" Help them name it. Not just "good/bad" but "excited," "annoyed," "proud," "bored." Then: "How strong, 1 to 10?" Don't judge or fix the feeling.`,
    watchFor: `Does their emotional vocabulary expand? Can they distinguish "frustrated" from "angry"? Can they name positive feelings beyond "happy"?`,
    oneLineToSay: `Feelings are information, not problems. Naming them is how we listen.`,
    trap: `Telling them what they're feeling. "You're not angry, you're tired." That teaches them to mistrust their own signals.`,
    adapt: {
      easier: `Pick from 4 options (happy/sad/angry/scared).`,
      harder: `Name the feeling AND its cause AND what it wants.`,
    },
    worksWellWith: ["stories", "talking", "any quiet moment"],
  },
  {
    id: "em2",
    title: "Big Feelings Pause",
    skill: "emotional",
    duration: 5,
    difficulty: 2,
    languageLoad: "medium",
    ageRange: [6, 10],
    requires: "nothing",
    description: `Teach a "pause and breathe" routine, practiced in calm so it's available in storm.`,
    hiddenCurriculum: `The 4-second gap between feeling and reacting is where all adult emotional intelligence lives. Most adults never developed it. Installing it at age 7 is gold.`,
    howTo: `When calm, teach them: when a big feeling comes, put a hand on belly, breathe in for 4, out for 6, then say "I feel ___." Practice 3 times in calm. Then USE it next time they're actually upset.`,
    watchFor: `Do they start using it on their own over weeks? That's the win.`,
    oneLineToSay: `The breath is the pause button. Use it before you press play on the reaction.`,
    trap: `Using it as a punishment in the moment ("go breathe!"). Make it an invitation, not a command. Sit and do it WITH them.`,
    adapt: {
      easier: `Just 3 breaths, no naming step.`,
      harder: `4-7-8 breathing, longer routine.`,
    },
    worksWellWith: ["any quiet routine", "bedtime"],
  },
  {
    id: "em3",
    title: "Other Person's Shoes",
    skill: "emotional",
    duration: 10,
    difficulty: 2,
    languageLoad: "high",
    ageRange: [6, 10],
    requires: "nothing",
    description: `Pick a real situation that happened today. Imagine how the OTHER person felt.`,
    hiddenCurriculum: `Empathy is not a feeling. It's a skill: the ability to construct another person's experience. This is how leaders, friends, and partners are built.`,
    howTo: `A fight with a friend, a teacher's scolding, even a TV character. Ask: "What do you think THEY were feeling? Why?" Don't lead them. Let them guess. Discuss without forcing them to agree with you.`,
    watchFor: `Genuine perspective-taking vs. just saying what you want to hear.`,
    oneLineToSay: `Every story has at least two insides. Both are real.`,
    trap: `Using this to make them apologize. The moment it becomes a lesson, perspective-taking dies.`,
    adapt: {
      easier: `Use a simple storybook character.`,
      harder: `A real conflict with multiple parties, name what each one felt.`,
    },
    worksWellWith: ["stories", "talking", "anything social"],
  },
  {
    id: "em4",
    title: "Feeling Weather Report",
    skill: "emotional",
    duration: 5,
    difficulty: 1,
    languageLoad: "medium",
    ageRange: [5, 10],
    requires: "nothing",
    description: `Each evening, both of you give your day a "weather": sunny, stormy, cloudy with sun.`,
    hiddenCurriculum: `Nuance. Most kids describe days as "good" or "bad." Weather metaphors teach that days have *parts*, that feelings shift within a day.`,
    howTo: `Before bed: "What was your weather today?" They say e.g. "Stormy in the morning, sunny by lunch." You do yours too. No fixing. Reflect: "Sounds like the morning was hard."`,
    watchFor: `Do they start being more nuanced than "good day / bad day"?`,
    oneLineToSay: `Weather changes inside the same day. So do we.`,
    trap: `Fixing the storm. "Why was it stormy?" with a solving tone teaches them to hide stormy moments. Just receive it.`,
    adapt: {
      easier: `Just one word.`,
      harder: `Weather + reason + what made it shift.`,
    },
    worksWellWith: ["bedtime", "talking"],
  },
  {
    id: "em5",
    title: "Anger Box",
    skill: "emotional",
    duration: 15,
    difficulty: 2,
    languageLoad: "low",
    ageRange: [6, 10],
    requires: "paper-pen",
    description: `Make a physical "anger box" of things they can do when angry. Build the list together.`,
    hiddenCurriculum: `Having pre-decided coping options removes the impossible task of inventing them mid-meltdown. Adults call this "regulation strategies." Kids call it the box.`,
    howTo: `When calm: "What helps you when you're really angry?" Brainstorm a list. Decorate a box. Put options inside on slips of paper (squeeze a pillow, draw the anger, count to 20, stomp 10 times). Use it next time.`,
    watchFor: `Do they go to the box on their own? That's the goal.`,
    oneLineToSay: `We make the plan when calm. Then we follow the plan when we're not.`,
    trap: `Imposing options they didn't pick. Their list, their box. Even if "scream into a pillow" sounds silly to you, write it down.`,
    adapt: {
      easier: `3 options, simple.`,
      harder: `Also make a "sad box" and "worried box."`,
    },
    worksWellWith: ["drawing", "crafts", "building"],
  },
  {
    id: "em6",
    title: "Apology Practice",
    skill: "emotional",
    duration: 10,
    difficulty: 3,
    languageLoad: "high",
    ageRange: [7, 10],
    requires: "nothing",
    description: `Teach the 4-part apology: what I did, why it was wrong, how it made you feel, what I'll do next time.`,
    hiddenCurriculum: `Real apologies are a skill, not a virtue. Most adults can't apologize properly. Installing this at 7 builds an unusual quality.`,
    howTo: `Practice with a hypothetical first: "Imagine you broke a friend's toy." Walk through: 1) I broke your toy. 2) I should have been careful. 3) I think it made you sad. 4) I'll be more careful. Then use the structure the next real time.`,
    watchFor: `Do they start apologizing more genuinely? Less defensively?`,
    oneLineToSay: `'Sorry' alone is a word. The four parts make it real.`,
    trap: `Forcing an apology to end a fight quickly. Real apologies take time. Better a slow real one than a fast fake one.`,
    adapt: {
      easier: `Just steps 1 and 4.`,
      harder: `Also practice receiving apologies: "Thank you. It hurt when..."`,
    },
    worksWellWith: ["social situations", "family"],
  },
  {
    id: "em7",
    title: "Story Feelings",
    skill: "emotional",
    duration: 10,
    difficulty: 1,
    languageLoad: "medium",
    ageRange: [5, 10],
    requires: "objects-at-home",
    description: `Read a story. Pause at key moments and ask what each character feels and why.`,
    hiddenCurriculum: `Practicing emotional reading on safe targets (story characters) before applying it to real people. Builds the muscle without the stakes.`,
    howTo: `Any story works. At conflict moments, pause: "How do you think she feels? What in the picture or words tells you?" Push for evidence, not just guesses.`,
    watchFor: `Use of evidence from the story. Range of emotions named.`,
    oneLineToSay: `We read faces in books to practice reading faces in life.`,
    trap: `Pre-stating the character's feeling. Let them guess first.`,
    adapt: {
      easier: `Very clear emotions, picture books.`,
      harder: `Complex stories with mixed feelings.`,
    },
    worksWellWith: ["stories", "reading", "drawing"],
  },
  {
    id: "em8",
    title: "Gratitude Three",
    skill: "emotional",
    duration: 5,
    difficulty: 1,
    languageLoad: "medium",
    ageRange: [5, 10],
    requires: "nothing",
    description: `Each night, 3 specific things they're grateful for. You do yours too.`,
    hiddenCurriculum: `Specificity is the antidote to generic optimism. Saying "I'm grateful for my family" is different from "I'm grateful that papa made jokes at dinner." The latter trains noticing.`,
    howTo: `Before bed: 3 specific things. Not "my family" but "when papa made jokes at dinner." You go first to model specificity. Don't accept generic answers. Gently push: "Tell me ONE moment."`,
    watchFor: `Specificity over time. Do they start noticing good moments AS they happen?`,
    oneLineToSay: `The day is full of moments. Most people miss them. We collect three.`,
    trap: `Making it a chore. If they're flat tired, skip a night. The practice is gentle, not mandatory.`,
    adapt: {
      easier: `1 thing.`,
      harder: `3 things + one thing you did well.`,
    },
    worksWellWith: ["bedtime", "talking"],
  },

  // ============================================================
  // THINKING CLARITY
  // ============================================================
  {
    id: "th1",
    title: "How Do We Know?",
    skill: "thinking",
    duration: 10,
    difficulty: 2,
    languageLoad: "high",
    ageRange: [7, 10],
    requires: "nothing",
    description: `When they state something as fact, gently ask "How do we know that?"`,
    hiddenCurriculum: `The single most important critical-thinking habit: distinguishing knowing from hearing-and-repeating. Adults who never developed this are vulnerable to misinformation their whole life.`,
    howTo: `Whenever they say something definite ("Sharks are scary," "Vegetables are bad," "Boys are stronger"), ask "How do we know that?" Don't argue. Just keep asking until they separate "I heard" from "I saw" from "I think."`,
    watchFor: `Do they start volunteering "I think" vs "I know"? That's metacognition starting.`,
    oneLineToSay: `There's a difference between knowing something and being told it. Most people forget that.`,
    trap: `Doing this aggressively when they say something cute or harmless. Use it 1-2 times a day, max. Otherwise it becomes nagging and they shut down.`,
    adapt: {
      easier: `Only once a day, on neutral topics.`,
      harder: `Also ask "What would change your mind?"`,
    },
    worksWellWith: ["stories", "talking", "news", "anything"],
  },
  {
    id: "th2",
    title: "Two Reasons Game",
    skill: "thinking",
    duration: 10,
    difficulty: 2,
    languageLoad: "high",
    ageRange: [6, 10],
    requires: "nothing",
    description: `For any "why" question, find TWO different possible reasons before settling on one.`,
    hiddenCurriculum: `Generating alternatives is the core of critical thinking. Most people stop at the first answer that feels right. This trains them not to.`,
    howTo: `Why is the sky blue? Why do kids fight? Why is mama tired? Insist on 2 possible reasons before they pick. "Yes, that's one. What's another?" Then: "Which seems more likely? Why?"`,
    watchFor: `Generating alternatives gets easier over weeks. That's the practice working.`,
    oneLineToSay: `First answer is rarely the best answer. Second one is where thinking starts.`,
    trap: `Pushing for the "right" second reason. Any second reason is fine. The muscle is the generation, not the accuracy.`,
    adapt: {
      easier: `You offer one reason, they offer one.`,
      harder: `3 reasons, then rank them.`,
    },
    worksWellWith: ["any conversation", "science", "stories"],
  },
  {
    id: "th3",
    title: "Sort the Same Things",
    skill: "thinking",
    duration: 15,
    difficulty: 2,
    languageLoad: "medium",
    ageRange: [6, 10],
    requires: "objects-at-home",
    description: `Take 10 random objects. Sort them. Then re-sort with a different rule. Then again.`,
    hiddenCurriculum: `Cognitive flexibility: the ability to see the same things multiple ways. This is the underlying skill behind creativity, debate, and good decision-making.`,
    howTo: `Gather 10 random items (toys, kitchen things, anything safe). They sort into groups. Ask: "What was your rule?" Then: "Now sort using a totally different rule." Aim for 3 different sorts.`,
    watchFor: `Flexibility of categories. Can they see the same thing multiple ways? Do they get more creative with rules?`,
    oneLineToSay: `Same things, different rules, different groups. That's how big thinkers think.`,
    trap: `Suggesting rules. Their rules, even if silly. Silly rules are creative rules.`,
    adapt: {
      easier: `6 items, 2 sorts.`,
      harder: `15 items, 5 sorts.`,
    },
    worksWellWith: ["building/lego", "organizing", "drawing"],
  },
  {
    id: "th4",
    title: "What's Missing?",
    skill: "thinking",
    duration: 10,
    difficulty: 2,
    languageLoad: "medium",
    ageRange: [6, 10],
    requires: "paper-pen",
    description: `Draw a familiar object together from memory. Then check what's actually missing.`,
    hiddenCurriculum: `We don't see what we look at every day. This activity creates the unsettling, useful realization that *attention is selective*.`,
    howTo: `Both draw the same thing from memory: a bicycle, your house, your school, a 100-rupee note. Then go look at the real thing. What did each of you miss? What's usually invisible to you?`,
    watchFor: `This builds observation AND the realization that we don't see everything.`,
    oneLineToSay: `We look at things every day without seeing them. Today we saw.`,
    trap: `Mocking what they missed. Compare what YOU missed too. This is humbling for everyone.`,
    adapt: {
      easier: `Simple objects (a spoon, a fork).`,
      harder: `Complex things (their classroom, a famous logo).`,
    },
    worksWellWith: ["drawing", "observation", "art"],
  },
  {
    id: "th5",
    title: "Same or Different?",
    skill: "thinking",
    duration: 10,
    difficulty: 2,
    languageLoad: "high",
    ageRange: [6, 10],
    requires: "nothing",
    description: `Pick two things. Find 5 ways they're the same and 5 ways they're different.`,
    hiddenCurriculum: `Analogy and contrast are foundational reasoning tools. Used by every scientist, lawyer, writer, designer.`,
    howTo: `Pick odd pairs (a cat and a car, a teacher and a book, the moon and a clock). List 5 similarities and 5 differences. Push past the obvious.`,
    watchFor: `Do they go beyond surface features (color, size) to function or behavior?`,
    oneLineToSay: `Everything is a little like everything else. And totally not.`,
    trap: `Picking boring similar pairs (apple/orange). Weirder pairs unlock weirder thinking.`,
    adapt: {
      easier: `3 each, similar pairs.`,
      harder: `8 each, weirder pairs, abstract things.`,
    },
    worksWellWith: ["stories", "animals", "anything"],
  },
  {
    id: "th6",
    title: "Cause and Effect Chain",
    skill: "thinking",
    duration: 10,
    difficulty: 2,
    languageLoad: "high",
    ageRange: [6, 10],
    requires: "nothing",
    description: `Pick a small event. Trace 5 things that happen because of it, like dominoes.`,
    hiddenCurriculum: `Early systems thinking. The world is connected; actions have ripples. Adults who don't see this make worse decisions.`,
    howTo: `"It rains heavily." Then what? "Roads get wet." Then? "Cars go slow." Then? "Papa is late." Then? Five links minimum. Then try going backward: what caused the rain?`,
    watchFor: `Length and quality of chain. Do branches start appearing (effect splits into multiple)?`,
    oneLineToSay: `One thing always touches the next thing. Smart people see the whole row.`,
    trap: `Correcting their logic when a link is shaky. Let weird chains run. The chain-building is the muscle.`,
    adapt: {
      easier: `3 links.`,
      harder: `8 links, branch into multiple effects.`,
    },
    worksWellWith: ["stories", "science", "anything observed"],
  },
  {
    id: "th7",
    title: "True, False, or Not Sure",
    skill: "thinking",
    duration: 10,
    difficulty: 2,
    languageLoad: "high",
    ageRange: [7, 10],
    requires: "nothing",
    description: `Tell them 5 statements. They say true / false / not sure. Defend each.`,
    hiddenCurriculum: `Comfort with not knowing. Many kids feel pressured to know. This teaches that "not sure" is honest, valid, and often the smartest answer.`,
    howTo: `Mix obvious truths, obvious falsehoods, and tricky ones: "All birds fly." "The sun is bigger than earth." "Spinach makes you strong." They pick one of 3 options AND explain. Reward "not sure," which is honest thinking.`,
    watchFor: `Use of "not sure." Many kids feel pressured to know. This teaches it's okay not to.`,
    oneLineToSay: `'Not sure' is the answer of careful thinkers.`,
    trap: `Treating "not sure" as worse than a wrong answer. It's better than a confident wrong answer.`,
    adapt: {
      easier: `3 statements, very clear.`,
      harder: `10 statements with nuance.`,
    },
    worksWellWith: ["stories", "science", "talking"],
  },
  {
    id: "th8",
    title: "Solve It Backward",
    skill: "thinking",
    duration: 15,
    difficulty: 3,
    languageLoad: "high",
    ageRange: [7, 10],
    requires: "nothing",
    description: `Pose a goal. Work backward step by step to figure out how to reach it.`,
    hiddenCurriculum: `Planning, executive function, and goal-orientation. Most adults can't reverse-engineer outcomes. This installs the habit early.`,
    howTo: `Goal: "We want to eat dinner at 8pm sharp." Work backward: serve at 8 → cook by 7:50 → start by 7:30 → vegetables ready by 7:25 → buy them by 7. This is planning thinking.`,
    watchFor: `Can they hold the goal in mind while working backward? That's executive function building.`,
    oneLineToSay: `Working from the end to the now is how plans get made.`,
    trap: `Doing the working-backward for them. Pause. Wait. Let them propose.`,
    adapt: {
      easier: `Simple 3-step goal.`,
      harder: `Complex goal with multiple paths and constraints.`,
    },
    worksWellWith: ["cooking", "baking", "planning", "anything sequential"],
  },

  // ============================================================
  // RESILIENCE
  // ============================================================
  {
    id: "re1",
    title: "The Hard Puzzle",
    skill: "resilience",
    duration: 25,
    difficulty: 3,
    languageLoad: "low",
    ageRange: [6, 10],
    requires: "objects-at-home",
    description: `A puzzle/task slightly above their level. You do NOT help unless they ask specifically.`,
    hiddenCurriculum: `Frustration tolerance. The ability to stay with a hard thing without quitting is more predictive of adult outcomes than IQ.`,
    howTo: `Pick something hard (a 60-piece puzzle if they do 30 easily, a math problem one grade up). Sit nearby but don't intervene. If they get frustrated, just acknowledge: "This is hard." Don't rescue. Stop only if they're genuinely overwhelmed.`,
    watchFor: `How long they persist before asking. Do they take breaks vs. quitting entirely?`,
    oneLineToSay: `Hard isn't a sign to quit. Hard is a sign you're growing.`,
    trap: `Rescuing too early. The discomfort IS the practice. Stay calm and present.`,
    adapt: {
      easier: `Only slightly above level, you nearby.`,
      harder: `Significantly harder, longer time.`,
    },
    worksWellWith: [
      "building/lego",
      "math",
      "drawing",
      "anything stretchable",
    ],
  },
  {
    id: "re2",
    title: "Try, Fail, Try Again",
    skill: "resilience",
    duration: 15,
    difficulty: 2,
    languageLoad: "medium",
    ageRange: [6, 10],
    requires: "objects-at-home",
    description: `A physical skill they've never done. Allow exactly 5 attempts. Celebrate trying, not success.`,
    hiddenCurriculum: `Decoupling effort from outcome. Most kids learn "try → win" or "try → quit." This teaches "try → adjust → try."`,
    howTo: `Catching a ball with one hand, balancing on one leg eyes closed, tying a specific knot. 5 attempts. Track each. Talk about what they changed between tries. Whether they succeed or not, the celebration is for trying again.`,
    watchFor: `Do they adjust strategy between tries or just repeat? That's learning.`,
    oneLineToSay: `What you changed between try 2 and try 3 was the learning.`,
    trap: `Praising success only. The whole point is to celebrate the trying.`,
    adapt: {
      easier: `Easier skill, 3 attempts.`,
      harder: `Harder skill, 10 attempts, track which strategies worked.`,
    },
    worksWellWith: ["sports", "balance", "music", "anything physical"],
  },
  {
    id: "re3",
    title: "The Mistake Story",
    skill: "resilience",
    duration: 10,
    difficulty: 1,
    languageLoad: "high",
    ageRange: [6, 10],
    requires: "nothing",
    description: `You tell them about a mistake YOU made today. They tell you one of theirs.`,
    hiddenCurriculum: `Mistakes become normal, discussable, and survivable. Most kids hide mistakes. Hidden mistakes ferment into shame.`,
    howTo: `Be honest. Real mistakes. "Today I was rude to a colleague and felt bad." Then ask them for one. The point: mistakes are normal and discussable. NEVER use their sharing against them later, not even gently.`,
    watchFor: `Trust building. Over weeks, do they share more openly?`,
    oneLineToSay: `Everyone makes mistakes. The thing that matters is whether we look at them.`,
    trap: `Using their shared mistake against them later. ONE betrayal here kills the practice forever.`,
    adapt: {
      easier: `You share, they just listen for the first few times.`,
      harder: `Also discuss what each of you would do differently.`,
    },
    worksWellWith: ["bedtime", "talking", "family time"],
  },
  {
    id: "re4",
    title: "Boredom Practice",
    skill: "resilience",
    duration: 25,
    difficulty: 2,
    languageLoad: "low",
    ageRange: [5, 10],
    requires: "nothing",
    description: `Set aside 20 minutes with no screens, no scheduled activity. They must figure out what to do.`,
    hiddenCurriculum: `Boredom is where imagination, self-direction, and inner life develop. Constantly-entertained kids never build these muscles.`,
    howTo: `Tell them: "Next 20 minutes, no screen, no plan. You decide what to do." Don't suggest. Let them be bored. Boredom is where creativity and self-direction grow. End by asking what they came up with.`,
    watchFor: `Does the time-to-discover-something shorten over weeks?`,
    oneLineToSay: `Boredom isn't an emergency. It's the door to imagination.`,
    trap: `Suggesting activities when they whine. The whining IS the practice. Hold the line.`,
    adapt: {
      easier: `Start with 10 minutes if very screen-conditioned.`,
      harder: `30+ minutes, weekly.`,
    },
    worksWellWith: ["any quiet time at home"],
  },
  {
    id: "re5",
    title: "Finish What You Started",
    skill: "resilience",
    duration: 15,
    difficulty: 2,
    languageLoad: "medium",
    ageRange: [6, 10],
    requires: "objects-at-home",
    description: `Pick something they abandoned. Today, finish it.`,
    hiddenCurriculum: `Many adults can't finish things. They had this hopping pattern installed in childhood and never unlearned it. Practicing closure is rare and valuable.`,
    howTo: `A half-built lego, an unfinished drawing, a puzzle. The rule: today we finish it, however small. Sit with them. If they resist, acknowledge: "It's hard to come back to old things." But finish.`,
    watchFor: `Their relationship with completion. Many kids hop activity to activity.`,
    oneLineToSay: `Things we finish change us. Things we drop don't.`,
    trap: `Picking too big a thing. Aim for 10-15 min of work left. Set them up to win.`,
    adapt: {
      easier: `Pick something with just 10 min of work left.`,
      harder: `A bigger abandoned project, multi-day.`,
    },
    worksWellWith: ["building/lego", "drawing", "crafts"],
  },
  {
    id: "re6",
    title: "Lose on Purpose",
    skill: "resilience",
    duration: 15,
    difficulty: 2,
    languageLoad: "low",
    ageRange: [6, 10],
    requires: "objects-at-home",
    description: `Play a game where they'll likely lose. Don't let them win.`,
    hiddenCurriculum: `Losing is a skill. Adults who never learned to lose well become adults who can't take feedback, can't admit mistakes, can't lose elections, jobs, or arguments gracefully.`,
    howTo: `Chess, cards, any board game. Don't throw the game. They need practice losing without it being a catastrophe. If they get upset, acknowledge calmly: "Losing is hard. It feels bad. Want to play again?"`,
    watchFor: `Recovery time. Does the upset get shorter over weeks?`,
    oneLineToSay: `Losing tells us what to practice. Winning just tells us we already knew it.`,
    trap: `Throwing the game to avoid a meltdown. The meltdown is part of the practice. Hold steady.`,
    adapt: {
      easier: `A short game first, build up.`,
      harder: `A tournament of 3 games, varied outcomes.`,
    },
    worksWellWith: ["games", "board games", "sports"],
  },
  {
    id: "re7",
    title: "The Cold Splash",
    skill: "resilience",
    duration: 5,
    difficulty: 2,
    languageLoad: "low",
    ageRange: [5, 10],
    requires: "nothing",
    description: `Wash face with cold water in morning. Notice the "ugh" then the "okay."`,
    hiddenCurriculum: `A felt experience of: *discomfort passes*. Most kids learn to avoid discomfort. Brief, safe, chosen discomfort teaches the opposite.`,
    howTo: `Just cold water on face, as morning routine. They notice: "It feels bad for 5 seconds. Then it feels good." This is a tiny experience of: discomfort passes. Don't force it; invite it.`,
    watchFor: `Do they start choosing small uncomfortable things on their own? That's the seed of grit.`,
    oneLineToSay: `The bad feeling didn't last. Most bad feelings don't.`,
    trap: `Making it punishment. Frame as a choice they get to make, not something done to them.`,
    adapt: {
      easier: `Just splash, optional.`,
      harder: `10-second cold shower (kid-decided).`,
    },
    worksWellWith: ["morning routine"],
  },
  {
    id: "re8",
    title: "Try the Hard Food",
    skill: "resilience",
    duration: 10,
    difficulty: 3,
    languageLoad: "medium",
    ageRange: [6, 10],
    requires: "objects-at-home",
    description: `One food they refuse. They take 3 bites mindfully. No pressure beyond that.`,
    hiddenCurriculum: `Tolerance for unfamiliar sensations applies way beyond food. Adults who never learned to try unfamiliar things stay stuck in narrow lives.`,
    howTo: `Not making them finish it. Just 3 mindful bites of something they avoid (bitter gourd, mushroom, etc). Describe taste and texture aloud. After 3 bites, they're free. Try again in a week.`,
    watchFor: `Tolerance for the unfamiliar. The food doesn't matter; the willingness does.`,
    oneLineToSay: `Brave isn't liking it. Brave is trying it.`,
    trap: `Making them finish. That kills the practice. 3 mindful bites, exit clean.`,
    adapt: {
      easier: `Just 1 bite, or smell only.`,
      harder: `Try a new cuisine entirely.`,
    },
    worksWellWith: ["eating", "mealtime"],
  },

  // ============================================================
  // CREATIVITY
  // ============================================================
  {
    id: "cr1",
    title: "20 Uses For This",
    skill: "creativity",
    duration: 10,
    difficulty: 2,
    languageLoad: "medium",
    ageRange: [6, 10],
    requires: "objects-at-home",
    description: `Pick one object. Come up with 20 unusual uses for it together.`,
    hiddenCurriculum: `Divergent thinking: generating many possibilities before evaluating. The first 5 ideas are common. The last 5 are creative. The skill is pushing past the obvious.`,
    howTo: `A brick, a sock, a spoon. List 20 uses. Silly ones count. "A brick is a... paperweight, doorstop, hammer, weight for exercise, building block..." Push past the obvious 5.`,
    watchFor: `Where ideas come from. The first 5 are common; the last 5 are creative.`,
    oneLineToSay: `Everyone gets the first five. The next fifteen are where creative people live.`,
    trap: `Filtering for "good" ideas. Bad ideas are required. Generating quantity creates quality.`,
    adapt: {
      easier: `10 uses, simple object.`,
      harder: `30 uses, weirder objects.`,
    },
    worksWellWith: ["building/lego", "art", "drawing"],
  },
  {
    id: "cr2",
    title: "What If The World Was...",
    skill: "creativity",
    duration: 10,
    difficulty: 2,
    languageLoad: "high",
    ageRange: [6, 10],
    requires: "nothing",
    description: `A "what if" question. Explore what would change in detail.`,
    hiddenCurriculum: `Counterfactual thinking: imagining how things could be different. This is the foundation of design, innovation, fiction, and strategy.`,
    howTo: `What if everyone could fly? What if water tasted different in every glass? What if you could only speak in songs? Pick one. Discuss: school, food, shops, family. How would each change?`,
    watchFor: `Do they extend the idea or stop at the surface?`,
    oneLineToSay: `Everything was once a 'what if' someone took seriously.`,
    trap: `Picking what-ifs that are too logical. Wilder is better. Kids need permission to think wildly.`,
    adapt: {
      easier: `Simple concrete what-if.`,
      harder: `2 what-ifs combined.`,
    },
    worksWellWith: [
      "stories",
      "sci-fi",
      "pretend play",
      "dinosaurs",
      "space",
    ],
  },
  {
    id: "cr3",
    title: "Invent A Creature",
    skill: "creativity",
    duration: 15,
    difficulty: 2,
    languageLoad: "high",
    ageRange: [6, 10],
    requires: "paper-pen",
    description: `Together, design an animal that lives in a specific weird place.`,
    hiddenCurriculum: `Constraint-driven creativity. Real creative work isn't free-form. It's solving for fit. Designing to constraints teaches functional creativity.`,
    howTo: `Pick a place: under the sea floor, inside a volcano, on a cloud. What does the animal eat? How does it move? What are its enemies? Draw it. Name it.`,
    watchFor: `Internal consistency: do the creature's features match its habitat?`,
    oneLineToSay: `Real creativity isn't 'whatever.' It's solving the puzzle of fitting in a strange place.`,
    trap: `Letting features be arbitrary. Push: "But how would that work in a volcano?"`,
    adapt: {
      easier: `Just one feature, like the eyes.`,
      harder: `An ecosystem of 3 creatures that depend on each other.`,
    },
    worksWellWith: ["drawing", "animals", "dinosaurs", "nature", "sci-fi"],
  },
  {
    id: "cr4",
    title: "Story From Three Words",
    skill: "creativity",
    duration: 10,
    difficulty: 2,
    languageLoad: "high",
    ageRange: [6, 10],
    requires: "nothing",
    description: `You give three random words. They make a story using all three.`,
    hiddenCurriculum: `Connecting unrelated things is where creativity lives. Forced juxtaposition is a known creativity tool used by writers and inventors.`,
    howTo: `Words like: "elephant, key, mountain." They tell (or you write) a story using all three. Can be short. Then give 3 more for a second story. Silly is good.`,
    watchFor: `How creatively they connect unrelated things. That's the core of creativity.`,
    oneLineToSay: `Three random things, one story. That's how new ideas get born.`,
    trap: `Picking related words. Unrelated is the whole point. The friction generates the creativity.`,
    adapt: {
      easier: `2 words, very short story.`,
      harder: `5 words, longer story with structure.`,
    },
    worksWellWith: ["stories", "drawing", "pretend play"],
  },
  {
    id: "cr5",
    title: "Re-Invent An Object",
    skill: "creativity",
    duration: 15,
    difficulty: 3,
    languageLoad: "high",
    ageRange: [7, 10],
    requires: "paper-pen",
    description: `Pick a common object. How would you redesign it for a different user?`,
    hiddenCurriculum: `Empathy + creativity = design. Understanding a user's constraints, then solving for them, is a complete creative discipline.`,
    howTo: `A chair for a giraffe. A toothbrush for an elephant. A backpack for someone with no hands. Sketch the new design. Solve the actual problems.`,
    watchFor: `Empathy for the user (understanding their constraints) + creative problem-solving.`,
    oneLineToSay: `Good design starts by asking what does THIS person need.`,
    trap: `Skipping the empathy step. The user constraints are the creative material. Start there.`,
    adapt: {
      easier: `Just one tweak to an existing design.`,
      harder: `Redesign for multiple users at once.`,
    },
    worksWellWith: ["drawing", "animals", "building/lego"],
  },
  {
    id: "cr6",
    title: "Open-Ended Building",
    skill: "creativity",
    duration: 25,
    difficulty: 1,
    languageLoad: "low",
    ageRange: [5, 10],
    requires: "objects-at-home",
    description: `Pure unstructured building time: lego, blocks, cardboard. No plan.`,
    hiddenCurriculum: `Self-direction. Most kids only build to instructions or examples. Free building activates a different muscle: starting from nothing.`,
    howTo: `Set out building materials. NO theme, NO goal, NO suggestion. Just "build whatever." You build too, separately. After 25 minutes, both share what you made.`,
    watchFor: `Independence of imagination. Do they look to you for ideas or generate their own?`,
    oneLineToSay: `Some of the best stuff in the world started with someone just making.`,
    trap: `Suggesting a theme to "help." The empty page is the practice.`,
    adapt: {
      easier: `Shorter time, one inspiration given.`,
      harder: `Add a constraint mid-session ("must move," "must include a story").`,
    },
    worksWellWith: ["building/lego", "drawing", "crafts"],
  },
  {
    id: "cr7",
    title: "The Bad Idea Game",
    skill: "creativity",
    duration: 10,
    difficulty: 2,
    languageLoad: "high",
    ageRange: [6, 10],
    requires: "nothing",
    description: `Brainstorm the WORST ideas to solve a problem. Then see if any contain a good idea.`,
    hiddenCurriculum: `Removing the fear of being wrong unlocks creativity. By making "bad" the goal, you destroy the inner editor that kills ideas before they're spoken.`,
    howTo: `Problem: "How to get to school faster?" Worst ideas: ride a snail, dig a tunnel, fly with balloons. List 10 terrible solutions. Then pick one and find what's GOOD about the bad idea.`,
    watchFor: `Risk-taking with ideas. Comfort with looking silly.`,
    oneLineToSay: `Sometimes the bad idea is hiding a good idea inside.`,
    trap: `Being too "good" with your own bad ideas. Match their silliness. Outrank them in absurdity.`,
    adapt: {
      easier: `5 bad ideas, you go first.`,
      harder: `20 bad ideas, find a hidden good one.`,
    },
    worksWellWith: ["stories", "anything"],
  },
  {
    id: "cr8",
    title: "Make Up A Song",
    skill: "creativity",
    duration: 15,
    difficulty: 3,
    languageLoad: "high",
    ageRange: [6, 10],
    requires: "nothing",
    description: `Make up a 4-line song about something boring (dishes, traffic, brushing teeth).`,
    hiddenCurriculum: `Comfort with being silly. Most kids self-edit too much by age 8. This loosens it. Adults who can't be silly can't be creative.`,
    howTo: `Pick a boring topic. Make a melody (use a known tune if helpful). Write 4 lines together. Perform it. The point: even boring things can be made fun.`,
    watchFor: `Comfort with being silly. Many kids self-edit too much. This loosens it.`,
    oneLineToSay: `Boring things are only boring until someone makes a song about them.`,
    trap: `Cringing at their silliness. Match it. Be sillier.`,
    adapt: {
      easier: `2 lines, you do most.`,
      harder: `8 lines with rhyme scheme.`,
    },
    worksWellWith: ["music", "dancing", "stories", "pretend play"],
  },

  // ============================================================
  // OBSERVATION
  // ============================================================
  {
    id: "ob1",
    title: "Memory Tray",
    skill: "observation",
    duration: 10,
    difficulty: 2,
    languageLoad: "low",
    ageRange: [6, 10],
    requires: "objects-at-home",
    description: `Put 10 random items on a tray. They look for 30 seconds. Cover. They recall.`,
    hiddenCurriculum: `Active observation + short-term memory + strategy. Doing this repeatedly forces the brain to develop chunking and grouping strategies.`,
    howTo: `Place 10 items on a tray (coin, key, pencil, etc). They study for 30 seconds. Cover. They list what they saw. Count how many. Try again next day with new items.`,
    watchFor: `Improvement over weeks. Do they develop strategies (group by type, mental image)?`,
    oneLineToSay: `Memory isn't just remembering. It's HOW you look in the first place.`,
    trap: `Adding pressure. This is play. Score goes up over weeks naturally.`,
    adapt: {
      easier: `6 items, 1 minute.`,
      harder: `15 items, 20 seconds.`,
    },
    worksWellWith: ["games", "building/lego"],
  },
  {
    id: "ob2",
    title: "What Changed?",
    skill: "observation",
    duration: 5,
    difficulty: 1,
    languageLoad: "medium",
    ageRange: [5, 10],
    requires: "nothing",
    description: `Look around the room. They close eyes. You change one thing. They spot it.`,
    hiddenCurriculum: `Baseline awareness. The ability to notice what's different requires first noticing what is. Develops the foundation of attention.`,
    howTo: `In any room, they look carefully for 30 seconds. Close eyes. You move/change ONE thing (turn a book, move a cushion). They open eyes and find it.`,
    watchFor: `How long to find it. Do they develop a scanning method?`,
    oneLineToSay: `Detectives start by knowing what was normal.`,
    trap: `Making the change too subtle. Start obvious. Build over time.`,
    adapt: {
      easier: `Obvious change.`,
      harder: `3 changes at once.`,
    },
    worksWellWith: ["games", "building/lego"],
  },
  {
    id: "ob3",
    title: "Sound Map",
    skill: "observation",
    duration: 10,
    difficulty: 2,
    languageLoad: "medium",
    ageRange: [6, 10],
    requires: "paper-pen",
    description: `Sit somewhere outside. Close eyes for 2 minutes. Draw a "map" of every sound's direction.`,
    hiddenCurriculum: `Auditory observation, usually neglected entirely. We mostly tune sounds out; this re-attunes the ear.`,
    howTo: `Park bench, balcony, terrace. Close eyes. Draw a circle on paper for you in the middle. Every sound you hear, mark its direction with an arrow and a word. Compare maps.`,
    watchFor: `How many sounds they distinguish. We mostly tune things out. This re-attunes.`,
    oneLineToSay: `The world is louder than we let ourselves hear.`,
    trap: `Talking during. Silent is the practice.`,
    adapt: {
      easier: `1 minute, just count sounds.`,
      harder: `5 minutes, more detail, classify (human/animal/machine/natural).`,
    },
    worksWellWith: ["outdoor exploring", "nature", "music"],
  },
  {
    id: "ob4",
    title: "Watch A Person",
    skill: "observation",
    duration: 10,
    difficulty: 2,
    languageLoad: "medium",
    ageRange: [7, 10],
    requires: "outdoors",
    description: `At a public place, pick a stranger. Watch them for 3 minutes. Guess their story.`,
    hiddenCurriculum: `Social observation. Reading people from their body, clothes, behavior. A core social skill for adult life.`,
    howTo: `Park, station, mall. Pick someone safe to observe from a distance. Watch 3 minutes. Discuss: what's their mood? Where are they going? What might their job be? Build a story from clues.`,
    watchFor: `Use of evidence, not just guessing. Detail of observations.`,
    oneLineToSay: `People give away their stories without saying anything. We just have to look.`,
    trap: `Mocking or staring. Teach respect: observation is private, never rude.`,
    adapt: {
      easier: `Just describe what they're wearing.`,
      harder: `Observe a group, infer relationships.`,
    },
    worksWellWith: ["outdoor exploring", "stories", "meeting people"],
  },
  {
    id: "ob5",
    title: "Re-Notice Your Home",
    skill: "observation",
    duration: 15,
    difficulty: 2,
    languageLoad: "high",
    ageRange: [6, 10],
    requires: "nothing",
    description: `Walk through your own house. Find 10 things you've never really looked at.`,
    hiddenCurriculum: `Habituation is the enemy of attention. Re-noticing a familiar place restores fresh sight.`,
    howTo: `Walk slowly, room by room. Find 10 things they've never really noticed (a stain pattern, a small scratch, a label, a hinge). Take note. Realize how much we don't see daily.`,
    watchFor: `Whether their "noticing radius" expands generally after this.`,
    oneLineToSay: `We see what we look for. Today we look for everything.`,
    trap: `Rushing. Slow is the entire practice.`,
    adapt: {
      easier: `5 things, one room.`,
      harder: `20 things, photograph each.`,
    },
    worksWellWith: ["drawing", "photography", "art"],
  },
  {
    id: "ob6",
    title: "Texture Hunt",
    skill: "observation",
    duration: 10,
    difficulty: 1,
    languageLoad: "medium",
    ageRange: [5, 10],
    requires: "nothing",
    description: `Find 10 different textures around the house. Describe each in detail.`,
    hiddenCurriculum: `Sensory vocabulary. Most kids stop at "rough/smooth." Building richer sensory language enriches both observation and expression.`,
    howTo: `Smooth, rough, fuzzy, sticky, cold, warm, bumpy. Find an example of each. They describe WHY it feels that way. Build vocabulary for sensory details.`,
    watchFor: `Range of words used. Most kids stop at smooth/rough. Push further.`,
    oneLineToSay: `There are a hundred kinds of touch. Most have no names yet.`,
    trap: `Accepting "soft" or "hard" as final answers. Push: "What KIND of soft?"`,
    adapt: {
      easier: `Just 5 textures.`,
      harder: `Add smells AND sounds (full sensory hunt).`,
    },
    worksWellWith: ["drawing", "art", "cooking"],
  },
  {
    id: "ob7",
    title: "Track Something All Day",
    skill: "observation",
    duration: 5,
    difficulty: 2,
    languageLoad: "medium",
    ageRange: [6, 10],
    requires: "paper-pen",
    description: `Pick one thing to count throughout the day. Compare guess vs reality.`,
    hiddenCurriculum: `Calibration: matching belief to reality. This is the underlying skill behind good judgment, forecasting, science.`,
    howTo: `Morning: "How many times do you think we'll say 'come on' today? Guess." All day, tally. Or: how many cars pass our window in 5 minutes at 3pm, 5pm, 7pm. Estimate first, then measure.`,
    watchFor: `Accuracy of estimation improves over time. That's calibration.`,
    oneLineToSay: `Your guesses get smarter when you check them. That's how knowing happens.`,
    trap: `Calling them wrong if they guess badly. The guess is data, not a grade.`,
    adapt: {
      easier: `Count one obvious thing.`,
      harder: `Track 3 things at once, predict ratios.`,
    },
    worksWellWith: ["science", "math", "anything observable"],
  },
  {
    id: "ob8",
    title: "Mood Detective",
    skill: "observation",
    duration: 10,
    difficulty: 3,
    languageLoad: "high",
    ageRange: [7, 10],
    requires: "nothing",
    description: `Watch family members today. Guess their mood from small signs, not words.`,
    hiddenCurriculum: `Calibrated empathy. Reading people accurately, then verifying. This is rare and powerful in adulthood.`,
    howTo: `Through the day, observe family without asking. "Mama seemed quiet. I think she's tired." Use evidence: her movements, her voice tone. Then check with her. Were you right?`,
    watchFor: `Calibration of emotional reading + empathy.`,
    oneLineToSay: `Most people don't say how they feel. Most people show it.`,
    trap: `Letting the observation become invasive ("I see you're sad" announced loudly). Keep it private and gentle.`,
    adapt: {
      easier: `Just one family member, one moment.`,
      harder: `Predict everyone's mood at dinner before it starts.`,
    },
    worksWellWith: ["family", "stories", "social"],
  },

  // ============================================================
  // DECISIVENESS
  // ============================================================
  {
    id: "de1",
    title: "You Pick Dinner",
    skill: "decisiveness",
    duration: 10,
    difficulty: 1,
    languageLoad: "medium",
    ageRange: [5, 10],
    requires: "nothing",
    description: `Today, they decide what the family eats for one meal. Real choice, real ownership.`,
    hiddenCurriculum: `Real-stakes decision making. Most kids only get fake choices ("which color shirt"). One real decision a week builds the muscle for adult life.`,
    howTo: `Give 3 realistic options for dinner. They choose. Whatever they choose, you eat. No second-guessing. They see: my choice matters, and choices have consequences (a family ate this because of me).`,
    watchFor: `Speed of decision. Anxiety or excitement? Over time, do they own choices?`,
    oneLineToSay: `Your choice is a real choice. We're all eating it.`,
    trap: `Overriding the choice if it's "wrong." That teaches the choice was fake. Honor the choice.`,
    adapt: {
      easier: `2 options.`,
      harder: `Open choice, must plan it including ingredients.`,
    },
    worksWellWith: ["cooking", "eating", "family"],
  },
  {
    id: "de2",
    title: "60 Second Choice",
    skill: "decisiveness",
    duration: 5,
    difficulty: 2,
    languageLoad: "medium",
    ageRange: [6, 10],
    requires: "nothing",
    description: `Give them 2 options. They have 60 seconds to decide AND say why.`,
    hiddenCurriculum: `Comfort with deciding under time pressure. Adults who can't do this become chronic procrastinators.`,
    howTo: `Two real options (which shirt? which snack? which park?). 60-second timer. They pick AND give a reason. Practice deciding under mild pressure. Don't reverse their choice afterward.`,
    watchFor: `Quality of reasons. Speed. Do they learn to commit?`,
    oneLineToSay: `Deciding is a skill. The faster you practice, the better you get.`,
    trap: `Reversing their choice later "for their good." That kills the practice.`,
    adapt: {
      easier: `90 seconds, 2 simple options.`,
      harder: `3 options, 30 seconds.`,
    },
    worksWellWith: ["anything choice-based"],
  },
  {
    id: "de3",
    title: "The Trade-Off",
    skill: "decisiveness",
    duration: 10,
    difficulty: 3,
    languageLoad: "high",
    ageRange: [7, 10],
    requires: "nothing",
    description: `Give a choice where both options have pros and cons. They must list trade-offs before choosing.`,
    hiddenCurriculum: `Understanding that all real choices have costs. Adults who never learned this become paralyzed or impulsive.`,
    howTo: `"You can have an extra hour of play OR an ice cream, not both." They must say: "If I pick play, I lose ice cream. If I pick ice cream, I lose play." Then choose. The point: real choices have costs.`,
    watchFor: `Can they hold both sides in mind? Many kids only see the gain side.`,
    oneLineToSay: `Every yes is also a no to something. Smart deciders see both.`,
    trap: `Sneakily giving them both. Defeats the practice.`,
    adapt: {
      easier: `Very clear trade-off.`,
      harder: `3 options with multiple trade-offs.`,
    },
    worksWellWith: ["anything daily"],
  },
  {
    id: "de4",
    title: "Plan The Day",
    skill: "decisiveness",
    duration: 15,
    difficulty: 2,
    languageLoad: "high",
    ageRange: [7, 10],
    requires: "paper-pen",
    description: `A weekend morning, they plan the family's day. Real plan, real execution.`,
    hiddenCurriculum: `Planning + ownership + reality testing. Their plan meets the real world, and they learn what worked and what didn't.`,
    howTo: `Sit with them. They decide: 3 activities, when, in what order. Write it. Then DO it (with reasonable flexibility). Debrief: what worked, what they'd change.`,
    watchFor: `Realism of plan. Do they learn from execution?`,
    oneLineToSay: `Plans meet reality and learn from it. That's how planning gets good.`,
    trap: `Overriding the plan when it's inconvenient. Honor it imperfectly rather than not at all.`,
    adapt: {
      easier: `Just 2 activities.`,
      harder: `Half-day with budget constraints (₹500 for the outing).`,
    },
    worksWellWith: ["weekends", "family time"],
  },
  {
    id: "de5",
    title: "Buy It Yourself",
    skill: "decisiveness",
    duration: 15,
    difficulty: 3,
    languageLoad: "high",
    ageRange: [7, 10],
    requires: "outdoors",
    description: `Give them ₹50. Send them into a shop to buy something specific. Stand outside.`,
    hiddenCurriculum: `Independent action in the real world. One of the most confidence-building moments a 7-year-old can have.`,
    howTo: `Pre-decide what they'll buy (bread, a specific snack). Give ₹50. They go alone or with you watching from distance. They talk to shopkeeper, take change, walk out. Big confidence builder.`,
    watchFor: `Independent action. The decision is the whole thing.`,
    oneLineToSay: `You did that without me. You can do more than you think.`,
    trap: `Hovering at the door. They need to feel alone.`,
    adapt: {
      easier: `You walk in with them, they handle only payment.`,
      harder: `They pick WHAT to buy with ₹100 within a category.`,
    },
    worksWellWith: ["outdoor exploring", "going to shops"],
  },
  {
    id: "de6",
    title: "Pick A Side",
    skill: "decisiveness",
    duration: 10,
    difficulty: 2,
    languageLoad: "high",
    ageRange: [7, 10],
    requires: "nothing",
    description: `Give them a debatable question. They must pick a side and defend it.`,
    hiddenCurriculum: `Taking a position. Many adults won't commit to a view on anything. Comfortably defending a position is a rare skill.`,
    howTo: `"Should kids have homework?" "Is summer better than winter?" "Are dogs better than cats?" They must commit to one side AND give 3 reasons. No "both" allowed. Then switch sides next time.`,
    watchFor: `Quality of argument. Comfort with picking a position.`,
    oneLineToSay: `Picking a side and defending it isn't the same as being right. It's a skill of its own.`,
    trap: `Letting them off the hook with "both." That defeats it.`,
    adapt: {
      easier: `Low-stakes preferences (favorite fruit).`,
      harder: `Real ethical dilemmas appropriate to age.`,
    },
    worksWellWith: ["any conversation", "stories"],
  },
  {
    id: "de7",
    title: "The Reversible Test",
    skill: "decisiveness",
    duration: 5,
    difficulty: 2,
    languageLoad: "high",
    ageRange: [7, 10],
    requires: "nothing",
    description: `Teach: small reversible decisions, decide fast. Big irreversible ones, decide slow.`,
    hiddenCurriculum: `A mental model that good decision-makers use throughout life. Speed-matched-to-stakes.`,
    howTo: `Discuss: "If you pick the wrong ice cream flavor, can we fix it? (Yes, next time.) If we cut your hair too short, can we fix it fast? (No, takes time.)" Practice categorizing daily choices: fast or slow?`,
    watchFor: `Do they start using this language themselves? That's the goal.`,
    oneLineToSay: `Reversible? Decide fast. Permanent? Decide slow.`,
    trap: `Over-explaining. Two examples, then practice.`,
    adapt: {
      easier: `Just two clear examples.`,
      harder: `Add medium decisions, discuss gray areas.`,
    },
    worksWellWith: ["any decision"],
  },
  {
    id: "de8",
    title: "Stick With It",
    skill: "decisiveness",
    duration: 10,
    difficulty: 2,
    languageLoad: "medium",
    ageRange: [6, 10],
    requires: "nothing",
    description: `They made a choice. Now sit with the consequence without complaining.`,
    hiddenCurriculum: `Accepting consequences. Adults who can't do this blame others endlessly. Sitting with your own choice is a deep adult skill.`,
    howTo: `They chose chips over chocolate. They chose the park over the mall. When they later regret it: don't reverse. Acknowledge: "Yeah, sometimes our choice isn't the best. That happens. Next time you'll have more information."`,
    watchFor: `Acceptance of consequences. This builds adult decision-making.`,
    oneLineToSay: `Living with your choice is part of choosing.`,
    trap: `Rescuing them from regret. Regret is the teacher here. Stay warm but firm.`,
    adapt: {
      easier: `Very low stakes only.`,
      harder: `Bigger choices, real consequences (within safety).`,
    },
    worksWellWith: ["daily life"],
  },
];

export const ACTIVITIES: Activity[] = ACTIVITIES_BASE.map((a) => {
  const example = ACTIVITY_EXAMPLES[a.id];
  if (!example) {
    throw new Error(`Missing example for activity "${a.id}".`);
  }
  const iconName = ACTIVITY_ICONS[a.id];
  if (!iconName) {
    throw new Error(`Missing iconName for activity "${a.id}".`);
  }
  const hook = ACTIVITY_HOOKS[a.id];
  if (!hook) {
    throw new Error(`Missing hook for activity "${a.id}".`);
  }
  const icon = ACTIVITY_TABLER_ICONS[a.id];
  if (!icon) {
    throw new Error(`Missing Tabler icon for activity "${a.id}".`);
  }
  return { ...a, example, iconName, hook, icon };
});

// ---------- helpers ----------

export function getActivityById(id: string): Activity | undefined {
  return ACTIVITIES.find((a) => a.id === id);
}

export function getActivitiesBySkill(skill: SkillKey): Activity[] {
  return ACTIVITIES.filter((a) => a.skill === skill);
}
