"use client";

import { useRouter } from "next/navigation";
import { useCallback, type ReactNode, type SVGProps } from "react";

import { IntroCarousel } from "@/components/intro/IntroCarousel";
import { INTRO_SCREENS } from "@/lib/content/intro";

/**
 * Illustrated variant: same body copy as baseline, with an additive line-art
 * SVG above each slide. Strokes use currentColor and inherit `text-ink` so
 * the illustrations re-skin themselves in dark mode without per-asset tweaks.
 *
 * /dev only. Compare with the other two in /dev/intro-compare.
 */
export default function IntroIllustratedPage() {
  const router = useRouter();
  const finish = useCallback(() => {
    router.push("/onboarding/parent");
  }, [router]);

  const illustrations: ReactNode[] = [
    <Ruler key="i1" />,
    <Silhouettes key="i2" />,
    <ParentChild key="i3" />,
    <Sun key="i4" />,
    <Heart key="i5" />,
  ];

  const slides = INTRO_SCREENS.map((screen, i) => (
    <article key={screen.id} className="flex flex-col items-center gap-8">
      <div
        aria-hidden
        className="flex h-[140px] w-full items-end justify-center text-ink"
      >
        {illustrations[i]}
      </div>
      <p className="text-center text-body-large text-ink">{screen.body}</p>
    </article>
  ));

  return <IntroCarousel slides={slides} onComplete={finish} />;
}

// ---------- inline SVG illustrations ----------
//
// All illustrations: 140px tall, thin (1.5) stroke, single color via
// `currentColor`. Drawn inline so they ship with the route and respond to
// theme changes for free. Generated by hand for this app, no external assets.

const STROKE = 1.5;
const SVG_PROPS: SVGProps<SVGSVGElement> = {
  width: 140,
  height: 140,
  viewBox: "0 0 140 140",
  fill: "none",
  stroke: "currentColor",
  strokeWidth: STROKE,
  strokeLinecap: "round",
  strokeLinejoin: "round",
};

function Ruler() {
  // Abstract measurement: a ruler with tick marks.
  return (
    <svg {...SVG_PROPS} role="img" aria-label="A ruler">
      <rect x={20} y={56} width={100} height={28} rx={3} />
      {Array.from({ length: 9 }, (_, i) => {
        const x = 28 + i * 11;
        const isLong = i % 2 === 0;
        return (
          <line
            key={i}
            x1={x}
            x2={x}
            y1={56}
            y2={56 + (isLong ? 12 : 7)}
          />
        );
      })}
      {/* A small upward "data" pulse above the ruler, hinting at metrics */}
      <polyline points="32,40 48,32 64,38 80,28 96,34 112,30" />
    </svg>
  );
}

function Silhouettes() {
  // Three abstract figures: heads + shoulders. No faces.
  return (
    <svg {...SVG_PROPS} role="img" aria-label="Three figures">
      {[28, 70, 112].map((cx, idx) => {
        const headR = idx === 1 ? 11 : 9;
        const shoulderW = idx === 1 ? 30 : 26;
        return (
          <g key={cx}>
            <circle cx={cx} cy={56} r={headR} />
            <path
              d={`M ${cx - shoulderW / 2} ${108} Q ${cx} ${72}, ${cx + shoulderW / 2} ${108}`}
            />
          </g>
        );
      })}
      {/* A subtle ground line */}
      <line x1={16} x2={124} y1={120} y2={120} strokeDasharray="2 4" />
    </svg>
  );
}

function ParentChild() {
  // Two figures, one tall, one small, holding hands at the middle.
  return (
    <svg {...SVG_PROPS} role="img" aria-label="Parent and child">
      {/* Parent */}
      <circle cx={56} cy={40} r={10} />
      <path d="M 38 96 Q 56 56, 74 96" />
      <line x1={56} y1={72} x2={78} y2={86} />
      {/* Child */}
      <circle cx={94} cy={66} r={7} />
      <path d="M 82 116 Q 94 78, 106 116" />
      <line x1={94} y1={88} x2={80} y2={86} />
      {/* Ground line */}
      <line x1={20} x2={124} y1={126} y2={126} strokeDasharray="2 4" />
    </svg>
  );
}

function Sun() {
  // A single calm circle with short rays: today's moment.
  return (
    <svg {...SVG_PROPS} role="img" aria-label="A small sun">
      <circle cx={70} cy={70} r={22} />
      {Array.from({ length: 8 }, (_, i) => {
        const angle = (i * Math.PI) / 4;
        const inner = 32;
        const outer = 44;
        const x1 = 70 + Math.cos(angle) * inner;
        const y1 = 70 + Math.sin(angle) * inner;
        const x2 = 70 + Math.cos(angle) * outer;
        const y2 = 70 + Math.sin(angle) * outer;
        return <line key={i} x1={x1} y1={y1} x2={x2} y2={y2} />;
      })}
    </svg>
  );
}

function Heart() {
  // A simple line-art heart for the closing promise.
  return (
    <svg {...SVG_PROPS} role="img" aria-label="A heart">
      <path
        d="M 70 102
           C 70 102, 30 78, 30 54
           C 30 40, 42 30, 54 30
           C 62 30, 68 34, 70 42
           C 72 34, 78 30, 86 30
           C 98 30, 110 40, 110 54
           C 110 78, 70 102, 70 102 Z"
      />
    </svg>
  );
}
